// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFaPnZugPYGtGkzXWOQV4FsIsM7gMUtig',
    appId: '1:743081391991:web:65c054485a13e1b559d372',
    messagingSenderId: '743081391991',
    projectId: 'aquarium-d2824',
    authDomain: 'aquarium-d2824.firebaseapp.com',
    storageBucket: 'aquarium-d2824.appspot.com',
    measurementId: 'G-YCJHM79QDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDreodjD2Kvq4iEs-cli4qM_2U0RmD6u4',
    appId: '1:743081391991:android:ced8e19f7cd2e20e59d372',
    messagingSenderId: '743081391991',
    projectId: 'aquarium-d2824',
    storageBucket: 'aquarium-d2824.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh-ovDl-0EOaZzZfOA-LkrBbnTsLEBlsU',
    appId: '1:743081391991:ios:e842d4fcee83065759d372',
    messagingSenderId: '743081391991',
    projectId: 'aquarium-d2824',
    storageBucket: 'aquarium-d2824.appspot.com',
    iosBundleId: 'com.example.aqua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh-ovDl-0EOaZzZfOA-LkrBbnTsLEBlsU',
    appId: '1:743081391991:ios:6d6e44660a096b7b59d372',
    messagingSenderId: '743081391991',
    projectId: 'aquarium-d2824',
    storageBucket: 'aquarium-d2824.appspot.com',
    iosBundleId: 'com.example.aqua.RunnerTests',
  );
}
